### ISSUE TITLE
Python 3.5 does not support f' format

### ISSUE THREAD

**Issue by anyeone** [labd/django-cognito-jwt#2]
Trying to include this library in my Python 3.5 project yields compiler errors inside Pycharm:

Invalid syntax:  Python 3.5 does not support 'f' format

 @cached_property
    def pool_url(self):
        return f'https://cognito-idp.%s.amazonaws.com/%s' % (
            self.aws_region, self.aws_user_pool)

**Comment by anyeone** [comment]
When I pulled the project locally into my source code, all I had to do was remove the f and it worked properly.

**Comment by mr337** [comment]
I got bit by this too. Still evaluating library and if it works be happy to put in a PR.

**Comment by mikedebock** [comment]
We just released v0.0.2, it should work with python 3.5 from now.
