### ISSUE TITLE
Using the Django admin interface

### ISSUE THREAD

**Issue by jgordor** [labd/django-cognito-jwt#32]
I have the django-cognito-jwt integrated with DRF, but when I try to access the /admin interface, it shows me id/password login form.

How can I login on the django admin interface?

Thanks!

**Comment by SureshDamera** [comment]
Hey @jgordor 

We also end up with the same problem. Did you resolve this issue?

**Comment by matiszz** [comment]
I am having the same issue, could you solve it?
